services:
  postgres-db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: remind_db
      POSTGRES_USER: remind_db
      POSTGRES_PASSWORD: ReMinD-TermPro0Ject-Gr0-u-P
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-boot-network

  springboot-app:
    build: .
    container_name: springboot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/remind_db
      SPRING_DATASOURCE_USERNAME: remind_db
      SPRING_DATASOURCE_PASSWORD: ReMinD-TermPro0Ject-Gr0-u-P
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    networks:
      - spring-boot-network

volumes:
  postgres_data:

networks:
  spring-boot-network:
